//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaBanco()
        {
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int CuentaBancoID { get; set; }
        public int BancoID { get; set; }
        public string UsuarioID { get; set; }
        public int EstadoCuentaBancoID { get; set; }
        public int MonedaID { get; set; }
        public string NumeroCuenta { get; set; }
        public string NombreTitular { get; set; }
        public string ApellidoTitular { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public decimal BalanceInicial { get; set; }
        public string Comentario { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Banco Banco { get; set; }
        public virtual EstadoCuentaBanco EstadoCuentaBanco { get; set; }
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
