//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaPrestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaPrestamo()
        {
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int CuentaPrestamoID { get; set; }
        public int MonedaID { get; set; }
        public string UsuarioID { get; set; }
        public Nullable<decimal> CapitalInicial { get; set; }
        public decimal TasaAnual { get; set; }
        public Nullable<int> PagosPorAno { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> NumeroPagos { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
