//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatronRecurrente
    {
        public int PatronRecurrenteID { get; set; }
        public int RecordatorioID { get; set; }
        public int TipoRecurrenciaID { get; set; }
        public Nullable<int> NumeroSeparaciones { get; set; }
        public Nullable<int> NumeroMaxOcurrencia { get; set; }
        public Nullable<int> DiaDeSemana { get; set; }
        public Nullable<int> SemanaDeMes { get; set; }
        public Nullable<int> DiaDeMes { get; set; }
        public Nullable<int> MesDeAno { get; set; }
    
        public virtual Recordatorio Recordatorio { get; set; }
        public virtual TipoRecurrencia TipoRecurrencia { get; set; }
    }
}
