//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Presupuesto()
        {
            this.PresupuestoCategoria = new HashSet<PresupuestoCategoria>();
        }
    
        public int PresupuestoID { get; set; }
        public int PeriodoTemporalID { get; set; }
        public string UsuarioID { get; set; }
        public string Nombre { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual PeriodoTemporal PeriodoTemporal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupuestoCategoria> PresupuestoCategoria { get; set; }
    }
}
