//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarjetaCredito()
        {
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int TarjetaCreditoID { get; set; }
        public string UsuarioID { get; set; }
        public int BancoID { get; set; }
        public int EstadoTarjetaCreditoID { get; set; }
        public int MonedaID { get; set; }
        public string NumeroTarjeta { get; set; }
        public string NombreTitular { get; set; }
        public string ApellidoTitular { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public int MarcaID { get; set; }
        public string CVC { get; set; }
        public decimal TasaEfectivaAnual { get; set; }
        public decimal DeudaInicial { get; set; }
        public decimal LimiteCredito { get; set; }
        public string Comentario { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Banco Banco { get; set; }
        public virtual EstadoTarjetaCredito EstadoTarjetaCredito { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
