//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.Recordatorio = new HashSet<Recordatorio>();
        }
    
        public int TransaccionID { get; set; }
        public string UsuarioID { get; set; }
        public Nullable<int> CuentaBancoID { get; set; }
        public Nullable<int> TarjetaCreditoID { get; set; }
        public Nullable<int> CuentaPrestamoID { get; set; }
        public Nullable<int> ContactoID { get; set; }
        public string No_Ref_Externo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> EFECTIVO { get; set; }
        public string Adjunto { get; set; }
        public Nullable<decimal> MontoIngreso { get; set; }
        public Nullable<decimal> MontroEgreso { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Contacto Contacto { get; set; }
        public virtual CuentaBanco CuentaBanco { get; set; }
        public virtual CuentaPrestamo CuentaPrestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recordatorio> Recordatorio { get; set; }
        public virtual TarjetaCredito TarjetaCredito { get; set; }
    }
}
