//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaPrestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaPrestamo()
        {
            this.Transaccions = new HashSet<Transaccion>();
        }
    
        public int CuentaPrestamoID { get; set; }
        public int MonedaID { get; set; }
        public string UsuarioID { get; set; }
        public Nullable<decimal> CapitalInicial { get; set; }
        public decimal TasaAnual { get; set; }
        public Nullable<int> PagosPorAno { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> NumeroPagos { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions { get; set; }
    }
}
