//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaBanco()
        {
            this.Transaccions = new HashSet<Transaccion>();
        }
    
        public int CuentaBancoID { get; set; }
        public int BancoID { get; set; }
        public string UsuarioID { get; set; }
        public int EstadoCuentaBancoID { get; set; }
        public int MonedaID { get; set; }
        public string NumeroCuenta { get; set; }
        public string NombreTitular { get; set; }
        public string ApellidoTitular { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public decimal BalanceInicial { get; set; }
        public string Comentario { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Banco Banco { get; set; }
        public virtual EstadoCuentaBanco EstadoCuentaBanco { get; set; }
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccions { get; set; }
    }
}
