//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanzasPersonalesEntities : DbContext
    {
        public FinanzasPersonalesEntities()
            : base("name=FinanzasPersonalesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Banco> Bancoes { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Contacto> Contactoes { get; set; }
        public virtual DbSet<CuentaBanco> CuentaBancoes { get; set; }
        public virtual DbSet<CuentaPrestamo> CuentaPrestamoes { get; set; }
        public virtual DbSet<EstadoCategoria> EstadoCategorias { get; set; }
        public virtual DbSet<EstadoCuentaBanco> EstadoCuentaBancoes { get; set; }
        public virtual DbSet<EstadoTarjetaCredito> EstadoTarjetaCreditoes { get; set; }
        public virtual DbSet<EstadoTarjetaDebito> EstadoTarjetaDebitoes { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<PatronRecurrente> PatronRecurrentes { get; set; }
        public virtual DbSet<PeriodoTemporal> PeriodoTemporals { get; set; }
        public virtual DbSet<Presupuesto> Presupuestoes { get; set; }
        public virtual DbSet<PresupuestoCategoria> PresupuestoCategorias { get; set; }
        public virtual DbSet<Recordatorio> Recordatorios { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TarjetaCredito> TarjetaCreditoes { get; set; }
        public virtual DbSet<TipoCategoria> TipoCategorias { get; set; }
        public virtual DbSet<TipoRecurrencia> TipoRecurrencias { get; set; }
        public virtual DbSet<Transaccion> Transaccions { get; set; }
    }
}
